### DISCUSSION TITLE
Add a list of Tracker URLs to config

### DISCUSSION THREAD

**Discussion by josecelano** [torrust/torrust-index-backend#439] [Feature requests]
Currently, you can set the associated tracker URL in the configuration:

```toml
[tracker]
url = "udp://tracker.torrust-demo.com:6969"
# ...
token_valid_seconds = 7257600
```

When you upload a torrent, the Index will include that tracker URL:

![image](https://github.com/torrust/torrust-index/assets/58816/6d19f953-d0b4-44a7-aff2-dfdb2264e143)

It would be nice to include a list of URLs for the same tracker, for example:

- udp://tracker.torrust-demo.com:6969
- http://tracker.torrust-demo.com:7070
- https://tracker.torrust-demo.com:7070

Does it make sense @WarmBeer?
