### ISSUE TITLE
Bug: `/torrents?page_size` parameter is not working as expected.

### ISSUE THREAD

**Issue by WarmBeer** [torrust/torrust-index-backend#114]
`GET http://localhost:3000/torrents?page_size=1` returns 2 results instead of 1.

**Comment by josecelano** [comment]
Hey @WarmBeer, [the minimum page size is set to 10.](https://github.com/torrust/torrust-index-backend/blob/develop/src/routes/torrent.rs#L306-L310).

Do you want to remove that rule?

**Comment by josecelano** [comment]
Hi @WarmBeer, let me know what your initial idea was, so I can continue with this issue.

**Comment by WarmBeer** [comment]
> Hey @WarmBeer, [the minimum page size is set to 10.](https://github.com/torrust/torrust-index-backend/blob/develop/src/routes/torrent.rs#L306-L310).
> 
> Do you want to remove that rule?

Hi @josecelano , I think the minimum can be removed and we should add a maximum page size if there isn’t already.

**Comment by josecelano** [comment]
> > Hey @WarmBeer, [the minimum page size is set to 10.](https://github.com/torrust/torrust-index-backend/blob/develop/src/routes/torrent.rs#L306-L310).
> > Do you want to remove that rule?
> 
> Hi @josecelano , I think the minimum can be removed and we should add a maximum page size if there isn’t already.

Should we make it an option in the settings?

```toml
[torrent]
max_torrent_page_size = 100
```

I think we could have one section per context (route group): `about`, `category`, `image_cache(proxy)`, `root`, `settings`, `torrent`, `user`.

Or we can have one single section of the whole API configuration:

```toml
[api]
max_torrent_page_size = 100
```

Or:

```toml
[api_limits]
max_torrent_page_size = 100
```

I prefer the `[api]` one. I think we do not have too many options.

By the way, I would move the option `torrent_info_update_interval`:

```toml
[database]
connect_url = "sqlite://storage/database/torrust_index_backend_e2e_testing.db?mode=rwc"
torrent_info_update_interval = 3600
```

from the `[database]` section to a new section `[tracker_importer]`, like this:

```toml
[database]
connect_url = "sqlite://storage/database/torrust_index_backend_e2e_testing.db?mode=rwc"

[tracker_importer]
torrent_info_update_interval = 3600
```

I think `[database]` should contain only the info needed to connect to the database.

Maybe we can move the `torrent_info_update_interval` to the new `[api]` section. But I think each worker/job should have its section.

- Main worker/job -> `[api]`
- Tracker importer worker/job -> `[tracker_importer]` or [`tracker_data_importer`]

I do not like the name [`tracker_data_importer`], but I can't come up with a better name bow.
