### ISSUE TITLE
Move config option `torrent_info_update_interval` to a new section

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-backend#143]
Move the configuration option `torrent_info_update_interval`:

```toml
[database]
connect_url = "sqlite://storage/database/torrust_index_backend_e2e_testing.db?mode=rwc"
torrent_info_update_interval = 3600
```

from the `[database]` section to a new section `[tracker_statistics_importer]`, like this:

```toml
[database]
connect_url = "sqlite://storage/database/torrust_index_backend_e2e_testing.db?mode=rwc"

[tracker_statistics_importer]
torrent_info_update_interval = 3600
```

as discussed [here](https://github.com/torrust/torrust-index-backend/issues/114#issuecomment-1535847945).
